include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_const: true
    unnecessary_new: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    prefer_relative_imports: true
    always_use_package_imports: false
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    sort_constructors_first: false
    type_annotate_public_apis: false
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
