preferred-supported-locales: [en, th, zh, de, fr, nl]
output-dir: ./lib/l10n/generated
arb-dir: ./lib/l10n
template-arb-file: intl_en.arb
output-localization-file: order_accounting_localizations.dart
output-class: OrderAccountingLocalizations
