name: growerp_order_accounting
resolution: workspace
description:
  A package providing order and accounting functions such as order, invoice,
  payments and ledger for the GrowERP system both for sales and purchase.
version: 1.12.0
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.10.0
  flutter: '>=3.33.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  growerp_core: ^1.12.0
  growerp_models: ^1.13.0
  growerp_user_company: ^1.12.0
  decimal: ^3.2.6
  intl: ^0.20.3
  global_configuration: ^2.0.0
  equatable: ^2.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  bloc_concurrency: ^0.3.0
  meta: ^1.19.0
  image_picker: ^1.2.4
  responsive_framework: ^1.5.1
  flutter_simple_treeview: ^3.0.2
  printing: ^5.14.3
  pdf: ^3.12.0
  image: ^4.3.0
  about: ^2.2.0
  shared_preferences: ^2.5.6
  stream_transform: ^2.1.2
  collection: ^1.19.1
  dio: ^5.11.1
  credit_card_validator: ^2.1.0
  url_launcher: ^6.3.3
  flutter_colorpicker: ^1.1.0
  from_css_color: ^2.0.0
  path_provider: ^2.1.6
  file_picker: ^13.1.0
  file_picker_platform_interface: ^4.0.0
  cross_file: ^0.3.5+5
  fast_csv: ^0.2.11
  archive: ^3.6.1
  scrollable_positioned_list: ^0.3.8
  universal_io: ^2.3.1
  flutter_test:
    sdk: flutter
  fl_chart: ^1.2.0
  home_widget: ^0.10.0
  go_router: ^17.5.0

dev_dependencies:
  integration_test:
    sdk: flutter
  mockito: ^5.8.1
  very_good_analysis: ^11.0.0
  bloc_test: ^10.0.0
  json_serializable: ^6.14.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
