// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'

let wait = 1000;
async function enterTextByKey(driver, key, value) {
  let fieldName = await driver.findElement(By.id(key));
  fieldName.clear();
  fieldName.sendKeys(value)
}

async function tapByKey(driver, key,) {
  await driver.findElement(By.id(key)).click()
  await driver.sleep(wait);
}

describe('basic', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {
      "email": "test92@example.com",
      "url": "http://100000.localhost:8080/"
    }
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('create order', async function () {
    await driver.get(vars.url)
    await driver.manage().window().setRect({ width: 1230, height: 861 })
    await driver.findElement(By.css("#recipeCarousel .carousel-item:nth-child(1) > .d-block:nth-child(2) .figure-img")).click()
    await driver.findElement(By.id("cartAdd")).click()
    await driver.findElement(By.id("cart-quantity")).click()
    await driver.sleep(wait);
    await driver.findElement(By.id("createAccount")).click()
    await driver.sleep(wait);
    await enterTextByKey(driver, 'firstName', 'John')
    await enterTextByKey(driver, 'lastName', 'Denver')
    await enterTextByKey(driver, 'email', vars.email)
    await tapByKey(driver, "create")
    // login
    let fieldName = await driver.findElement(By.id("username"));
    fieldName.clear();
    fieldName.sendKeys(vars.email)
    await driver.findElement(By.id("loginButton")).click()
    await driver.sleep(wait);
    // checkout
    await driver.findElement(By.id("checkOut")).click()
    await driver.sleep(wait);
    // address
    await driver.findElement(By.id("newAddress")).click()
    await driver.sleep(wait);
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("qqq")
    await driver.findElement(By.id("attention")).click()
    await driver.findElement(By.id("attention")).sendKeys("qqq")
    await driver.findElement(By.id("address1")).click()
    await driver.findElement(By.id("address1")).sendKeys("qqq")
    await driver.findElement(By.id("city")).click()
    await driver.findElement(By.id("city")).sendKeys("qqqqq")
    await driver.findElement(By.id("postalcode")).click()
    await driver.findElement(By.id("postalcode")).sendKeys("3333333")
    await driver.findElement(By.id("updateAddress")).click()
    await driver.sleep(wait);
    await driver.findElement(By.id("addressCheckmark")).click()
    await driver.findElement(By.id("contAddress")).click()
    /// method
    await driver.sleep(wait);
    await driver.findElement(By.id("contSM")).click()
    // CC
    await driver.sleep(wait);
    await driver.findElement(By.id("addCreditCard")).click()
    await driver.findElement(By.id("nameCard")).click()
    await driver.findElement(By.id("nameCard")).sendKeys("qqqq")
    await driver.findElement(By.id("card")).click()
    await driver.findElement(By.id("card")).sendKeys("5414963712405156")

    await driver.findElement(By.id("month")).sendKeys("05")
    await driver.findElement(By.id("year")).sendKeys("2025")
    await driver.findElement(By.id("address")).sendKeys("qqq, qqq, qqqqq")
    await driver.findElement(By.id("updateCC")).click()

    await driver.findElement(By.id("cvv")).sendKeys("111")
    await driver.sleep(wait);
    await driver.findElement(By.id("contCC")).click()
    await driver.findElement(By.id("placeOrder")).click()
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
