arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: assessment_localizations.dart
output-class: AssessmentLocalizations
output-dir: lib/l10n/generated
preferred-supported-locales: [es, en, th, zh, de, fr, nl]
