name: growerp_demos
resolution: workspace
description: Demo runners and demo list screen for the GrowERP system.
version: 1.0.0
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: ^3.10.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  growerp_catalog: ^1.10.5
  growerp_manufacturing: ^1.0.0
  growerp_manuf_liner: ^1.0.0
  growerp_order_accounting: ^1.0.0
  decimal: ^3.2.4
  dio: ^5.4.3
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.0.0

flutter:
  uses-material-design: true
