preferred-supported-locales: [en, th, de]
output-dir: ./lib/l10n/generated
arb-dir: ./lib/l10n
template-arb-file: intl_en.arb
output-localization-file: marketing_localizations.dart
output-class: MarketingLocalizations
