preferred-supported-locales: [en, th]
output-dir: ./lib/l10n/generated
arb-dir: ./lib/l10n
template-arb-file: intl_en.arb
output-localization-file: user_company_localizations.dart
output-class: UserCompanyLocalizations