name: growerp_rest
description: The GrowERP rest interface
version: 1.0.0
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter: 
    sdk: flutter
  decimal: ^2.1.0
  equatable: ^2.0.5
  meta: ^1.3.0
  date_utils: ^0.2.0
  flutter_lints: ^2.0.1
  json_annotation: ^4.7.0
  dio: ^5.3.3
  freezed_annotation: ^2.0.3
dev_dependencies: 
  freezed: ^2.0.3
  mockito: ^5.0.2
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
