name: website
description: The Growerp.org website.
version: 0.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/growerp.png
    - assets/moquiLogo.png
    - assets/ofbizLogo.png
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
