arb-dir: lib/l10n
template-arb-file: core_en.arb
output-localization-file: core_localizations.dart
output-class: CoreLocalizations
output-dir: lib/l10n/generated
preferred-supported-locales: [en, th, zh, de]
