name: order_accounting_example
version: 0.0.0+0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  growerp_order_accounting:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
flutter_intl:
  enabled: true
