name: order_accounting_example
version: 0.0.0+0
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  growerp_order_accounting:
    path: ../
  growerp_inventory: ^1.9.0
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol_finders: ^2.1.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
flutter_intl:
  enabled: true
