arb-dir: packages/growerp_core/lib/l10n
template-arb-file: core_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
output-dir: packages/growerp_core/lib/l10n
