name: growerp
repository: https://github.com/growerp/growerp

packages:
  - packages/admin
  - packages/hotel
  - packages/freelance
  - packages/growerp*
  - packages/growerp*/*example

ide:
  intellij:
    enabled: false
    
scripts:
  analyze:
    exec: dart analyze .
    description: Analyse all packages for possible problems.
  build:
    description: build_runner build all modules.
    run: "flutter pub run build_runner build --delete-conflicting-outputs"
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: build_runner     
  buildclean:
    description: build_runner clean.
    run: "flutter pub run build_runner clean"
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: build_runner     
  watch:
    description: watch package.
    run: "dart run build_runner watch"
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: build_runner     
  l10n:
    description: Generates l10n for all app packages.
    run: "flutter gen-l10n"
    exec:
      failFast: true
    packageFilters:
      fileExists: "l10n.yaml"
      
  test_package:
    description: run all integration tests.
    run: "flutter test integration_test"
    exec:
      orderDependents: true
      concurrency: 1
    packageFilters:
      dirExists: "integration_test"
      scope: "*_example"
  test:
    description: run all app and package tests.
    run: "flutter test integration_test"
    exec:
      orderDependents: true
      concurrency: 1
    packageFilters:
      dirExists: "integration_test"

