name: website_example
description: A example project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  growerp_website:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cfg/
    - ./
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark100.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/infoGrey.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/chatGrey.png