preferred-supported-locales: [en, th, zh, de, fr]
output-dir: ./lib/l10n/generated
arb-dir: ./lib/l10n
template-arb-file: intl_en.arb
output-localization-file: catalog_localizations.dart
output-class: CatalogLocalizations
