name: inventory_example
description: A example project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  growerp_inventory:
    path: ../

  flutter_test:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg

