arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: hotel_localizations.dart
output-class: HotelLocalizations
output-dir: lib/l10n/generated
preferred-supported-locales: [es, en, th, zh, de, fr, nl]
