name: core
description: The Core of the GrowERP frontend.
version: 0.3.0+1
homepage: https://www.growerp.org
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  decimal: ^2.1.0
  reorderables:
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  meta: ^1.3.0
  image_picker: ^0.8.5
  responsive_framework: ^0.2.0
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  dropdown_search: ^4.0.1
  printing: ^5.9.2
  pdf: ^3.3.0
  about: ^2.1.1
  flutter_phoenix: ^1.0.0
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.0.15
  date_utils: ^0.2.0

  #NETWORK
  json_annotation: ^4.4.0
  dio: ^4.0.4

  #UTILITIES
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3
  credit_card_validator: ^2.0.1
  markdown_widget: ^1.2.8
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.0.3
  from_css_color: ^2.0.0
  path_provider: ^2.0.11
  file_picker: ^5.0.1
  fast_csv: ^0.1.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.2
  very_good_analysis: ^3.0.0
  bloc_test: ^9.0.1
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.4
  json_serializable: ^6.2.0
  dependency_validator: ^3.2.0
# run dependency validator: flutter pub run dependency_validator


flutter:
  uses-material-design: true
# from https://www.flaticon.com/
