/*
 * This GrowERP software is in the public domain under CC0 1.0 Universal plus a
 * Grant of Patent License.
 * 
 * To the extent possible under law, the author(s) have dedicated all
 * copyright and related and neighboring rights to this software to the
 * public domain worldwide. This software is distributed without any
 * warranty.
 * 
 * You should have received a copy of the CC0 Public Domain Dedication
 * along with this software (see the LICENSE.md file). If not, see
 * <http://creativecommons.org/publicdomain/zero/1.0/>.
 */

import groovy.xml.XmlSlurper
import org.moqui.context.ExecutionContext

// Get ExecutionContext
ExecutionContext ec = context.ec ?: context

// ownerPartyId and pseudoId are set by the service definition before this script runs
ec.logger.info("importGeneratedLandingPage called with:")
ec.logger.info("  ownerPartyId: ${ownerPartyId}")
ec.logger.info("  pseudoId: ${pseudoId}")
ec.logger.info("  xmlPath: ${xmlPath}")

if (!ownerPartyId) {
    ec.message.addError("ownerPartyId is null/empty - this should have been set by the service definition")
    return
}

if (!pseudoId) {
    ec.message.addError("pseudoId is null/empty - this should have been generated by getNext#PseudoId service")
    return
}

try {
    ec.logger.info("Importing generated landing page from: ${xmlPath}")
    
    // Step 1: Validate and parse XML file
    File xmlFile = new File(xmlPath)
    if (!xmlFile.exists()) {
        ec.message.addError("XML file not found: ${xmlPath}")
        return
    }
    
    ec.logger.info("Parsing XML file to extract landing page data")
    
    // Parse XML using XmlSlurper (Groovy built-in)
    def xmlSlurper = new XmlSlurper()
    def xmlRoot = xmlSlurper.parse(xmlFile)
    
    // The root is <entity-facade-xml>, we need to get the LandingPage child element
    def landingPageElement = xmlRoot.'growerp.landing.LandingPage'[0]
    def pageSectionList = xmlRoot.'growerp.landing.PageSection'
    def credibilityElement = xmlRoot.'growerp.landing.CredibilityInfo'[0]
    def statisticList = credibilityElement?.'growerp.landing.CredibilityStatistic'
    
    if (!landingPageElement) {
        ec.message.addError("Invalid XML structure - growerp.landing.LandingPage element not found")
        return
    }
    
    ec.logger.info("Parsed XML - title: ${landingPageElement.@title}, headline: ${landingPageElement.@headline}")
    
    // Step 2: Check if landing page already exists with this pseudoId
    def landingPages_xafind = ec.entity.find("growerp.landing.LandingPage")
        .condition((org.moqui.entity.EntityCondition) ec.entity.conditionFactory.makeActionConditionDirect("ownerPartyId", "equals", ownerPartyId, "DEMO", null, false, false, false, "false"))
        .condition((org.moqui.entity.EntityCondition) ec.entity.conditionFactory.makeActionConditionDirect("pseudoId", "equals", pseudoId, null, null, false, false, false, "false"))
    def landingPages = landingPages_xafind.list()
    
    if (landingPages && !landingPages.isEmpty()) {
        ec.message.addError("Landing page with pseudoId ${pseudoId} already exists for owner ${ownerPartyId}")
        return
    }
    
    // Step 3: Create landing page with real ownerPartyId and pseudoId
    ec.logger.info("Creating landing page with ownerPartyId=${ownerPartyId}, pseudoId=${pseudoId}")
    
    def landingPageData = [
        title: landingPageElement.@title.toString(),
        headline: landingPageElement.@headline.toString(),
        subheading: landingPageElement.@subheading.toString(),
        hookType: landingPageElement.@hookType?.toString() ?: "results",
        status: landingPageElement.@status?.toString() ?: "DRAFT",
        ownerPartyId: ownerPartyId,
        pseudoId: pseudoId
    ]
    
    def newPage = [:]
    if (true) {
        def call_service_result = ec.service.sync().name("create#growerp.landing.LandingPage")
            .parameters(landingPageData).call()
        if (newPage != null) { if (call_service_result) newPage.putAll(call_service_result) } else { newPage = call_service_result }
        if (ec.message.hasError()) return
    }
    
    def pageId = newPage.landingPageId
    ec.logger.info("Created landing page: ID=${pageId}, ownerPartyId=${ownerPartyId}, pseudoId=${pseudoId}")
    
    // Step 4: Create page sections linked to landing page
    ec.logger.info("Creating ${pageSectionList.size()} page sections for landing page ${pageId}")
    
    def sectionCount = 0
    def section_index = 0
    def _sectionIterator = pageSectionList.iterator()
    while (_sectionIterator.hasNext()) {
        def sectionElement = _sectionIterator.next()
        def section_has_next = _sectionIterator.hasNext()
        
        // Get next pseudoId for page section
        if (true) {
            def call_service_result = ec.service.sync().name("growerp.100.GeneralServices100.getNext#PseudoId")
                .parameters([ownerPartyId: ownerPartyId, seqName: 'pageSection']).call()
            if (context != null) { if (call_service_result) context.putAll(call_service_result) } else { context = call_service_result }
            if (ec.message.hasError()) return
        }
        
        def sectionData = [
            landingPageId: pageId,
            sectionTitle: sectionElement.@sectionTitle.toString(),
            sectionDescription: sectionElement.@sectionDescription.toString(),
            sectionSequence: sectionElement.@sectionSequence?.toString()?.toInteger() ?: section_index + 1,
            pseudoId: seqNum
        ]
        
        if (true) {
            def call_service_result = ec.service.sync().name("create#growerp.landing.PageSection")
                .parameters(sectionData).call()
            if (context != null) { if (call_service_result) context.putAll(call_service_result) } else { context = call_service_result }
            if (ec.message.hasError()) return
        }
        
        section_index++
        sectionCount++
    }
    
    ec.logger.info("Created ${sectionCount} page sections")
    
    // Step 5: Create credibility info linked to landing page
    def credibilityCount = 0
    def credibilityId = null
    if (credibilityElement?.name() == 'growerp.landing.CredibilityInfo') {
        ec.logger.info("Creating credibility info for landing page ${pageId}")
        
        // Get next pseudoId for credibility info
        if (true) {
            def call_service_result = ec.service.sync().name("growerp.100.GeneralServices100.getNext#PseudoId")
                .parameters([ownerPartyId: ownerPartyId, seqName: 'credibilityInfo']).call()
            if (context != null) { if (call_service_result) context.putAll(call_service_result) } else { context = call_service_result }
            if (ec.message.hasError()) return
        }
        
        def credibilityData = [
            landingPageId: pageId,
            creatorBio: credibilityElement.@creatorBio?.toString(),
            backgroundText: credibilityElement.@backgroundText?.toString(),
            pseudoId: seqNum
        ]
        
        if (true) {
            def call_service_result = ec.service.sync().name("create#growerp.landing.CredibilityInfo")
                .parameters(credibilityData).call()
            if (context != null) { if (call_service_result) context.putAll(call_service_result) } else { context = call_service_result }
            if (ec.message.hasError()) return
            credibilityId = call_service_result?.credibilityInfoId
        }
        
        credibilityCount = 1
        
        // Step 6: Create credibility statistics linked to credibility info
        if (credibilityId && statisticList) {
            ec.logger.info("Creating ${statisticList.size()} credibility statistics for credibility ${credibilityId}")
            
            def statCount = 0
            def statistic_index = 0
            def _statisticIterator = statisticList.iterator()
            while (_statisticIterator.hasNext()) {
                def statElement = _statisticIterator.next()
                def statistic_has_next = _statisticIterator.hasNext()
                
                def statData = [
                    credibilityInfoId: credibilityId,
                    statistic: statElement.@statistic?.toString(),
                    sequence: statElement.@sequence?.toString()?.toInteger() ?: statistic_index + 1
                ]
                
                if (true) {
                    def call_service_result = ec.service.sync().name("create#growerp.landing.CredibilityStatistic")
                        .parameters(statData).call()
                    if (context != null) { if (call_service_result) context.putAll(call_service_result) } else { context = call_service_result }
                    if (ec.message.hasError()) return
                }
                
                statistic_index++
                statCount++
            }
            
            ec.logger.info("Created ${statCount} credibility statistics")
        }
    }
    
    // Step 7: Get final landing page data using the proper service
    ec.logger.info("Retrieving formatted landing page data for ID: ${pageId}, ownerPartyId: ${ownerPartyId}")
    
    def getLandingPageResult = ec.service.sync().name("growerp.100.LandingPageServices100.get#LandingPage")
        .parameters([landingPageId: pageId, ownerPartyId: ownerPartyId])
        .call()
    
    ec.logger.info("get#LandingPage returned successfully")
    ec.logger.info("Landing page object type: ${getLandingPageResult.landingPage?.getClass()?.name}")
    ec.logger.info("Landing page keys: ${getLandingPageResult.landingPage?.keySet()}")
    ec.logger.info("Landing page size: ${getLandingPageResult.landingPage?.size()}")
    if (getLandingPageResult.landingPage) {
        ec.logger.info("Landing page ID from map: ${getLandingPageResult.landingPage.landingPageId}")
        ec.logger.info("Landing page title from map: ${getLandingPageResult.landingPage.title}")
        ec.logger.info("Landing page sections count: ${getLandingPageResult.landingPage.sections?.size()}")
    }
    
    ec.logger.info("Import statistics: landingPages=1, sections=${sectionCount}, credibilityItems=${credibilityCount}")
    
    // Step 8: Clean up temporary XML file
    try {
        xmlFile.delete()
        ec.logger.info("Cleaned up temporary XML file: ${xmlPath}")
    } catch (Exception delException) {
        ec.logger.warn("Could not delete temporary file: ${xmlPath}", delException)
    }
    
    // Set output parameters - these will be returned as the REST response
    context.landingPage = getLandingPageResult.landingPage
    context.itemsCreated = 1
    context.sectionsCreated = sectionCount
    context.credibilityItemsCreated = credibilityCount
    context.ctasCreated = 0
    
    ec.logger.info("Service returning landingPage with title: ${getLandingPageResult.landingPage?.title}")
    ec.logger.info("Service complete - setting response context")
    
} catch (Exception e) {
    ec.logger.error("Error importing landing page", e)
    ec.logger.error("Error details: ${e.message}")
    ec.logger.error("Error class: ${e.getClass().name}")
    ec.message.addError("Error importing landing page: ${e.message}")
}

return
