name: ecommerce
description: A new Flutter package project.
version: 0.0.1
homepage: https://ecommerce.growerp.org
publish_to: none


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter: 
    sdk: flutter
  decimal: ^2.1.0
  global_configuration: ^2.0.0
  equatable: ^2.0.3
  dio: ^5.3.3
  flutter_bloc: ^8.0.0
  meta: ^1.3.0
  shared_preferences: ^2.0.5
  about: ^2.0.0
  animations: ^2.0.0
  responsive_framework: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_driver:
#    sdk: flutter
#  integration_test:^1.0.2+2
  mockito: ^5.0.2
  very_good_analysis: ^2.0.0

  bloc_test: ^9.0.1
#  flutter_launcher_icons: ^0.9.0

# to run icons: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/growerp.jpg"

flutter:
  uses-material-design: true
# from https://www.flaticon.com/
# https://creativemarket.com/eucalyp Eucalyp
  assets:
    - assets/cfg/
    - packages/growerp_core/images/about.png
    - packages/growerp_core/images/aboutGrey.png
    - packages/growerp_core/images/accounting.png
    - packages/growerp_core/images/category.png
    - packages/growerp_core/images/categoryGrey.png
    - packages/growerp_core/images/addImage.png
    - packages/growerp_core/images/categories.png
    - packages/growerp_core/images/company.png
    - packages/growerp_core/images/favicon-32x32.png
    - packages/growerp_core/images/growerpPlaystore.png
    - packages/growerp_core/images/orderGrey.png
    - packages/growerp_core/images/supplierGrey.png
    - packages/growerp_core/images/crmGrey.png
    - packages/growerp_core/images/growerp1024x500.jpg
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/order.png
    - packages/growerp_core/images/supplier.png
    - packages/growerp_core/images/accountingGrey.png
    - packages/growerp_core/images/category.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp50x50.jpg
    - packages/growerp_core/images/infoGrey.png
    - packages/growerp_core/images/personInfo.png
    - packages/growerp_core/images/up-arrow.png
    - packages/growerp_core/images/accounting.png
    - packages/growerp_core/images/chatGrey.png
    - packages/growerp_core/images/dashBoardGrey.png
    - packages/growerp_core/images/growerp512x512.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/productsGrey.png
    - packages/growerp_core/images/usersGrey.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/dashBoard.png
    - packages/growerp_core/images/growerpAppstore.png
    - packages/growerp_core/images/myInfoGrey.png
    - packages/growerp_core/images/products.png
    - packages/growerp_core/images/users.png
    - packages/growerp_core/images/categoriesGrey.png
    - packages/growerp_core/images/companyGrey.png
    - packages/growerp_core/images/export.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/myInfo.png
    - packages/growerp_core/images/search.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/chatGrey.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/infoGrey.png
