#!/bin/bash

docker build \
    --build-arg PAT=$PAT \
    --build-arg DOCKER_TAG=$DOCKER_TAG \
    --no-cache \
    -t $IMAGE_NAME \
    -f $DOCKERFILE_PATH .

docker tag $IMAGE_NAME $DOCKER_REPO
docker push $DOCKER_REPO
