#!/bin/bash

# create latest tag
docker build \
    --build-arg PAT=$PAT \
    --build-arg DOCKER_TAG=$DOCKER_TAG \
    -t $DOCKER_REPO \
    -f $DOCKERFILE_PATH .

# create version tag
docker tag $DOCKER_REPO $IMAGE_NAME
docker push $IMAGE_NAME
