name: moqui
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  shared_preferences: ^0.5.12+2
  global_configuration: ^1.6.0
  http: ^0.12.2
  models:
#    path: ../moqui
    git:
      url: https://github.com/growerp/growerp.git
      ref: packages
      path: models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test_coverage: ^0.4.0

flutter:

