preferred-supported-locales: [en, th]
output-dir: ./lib/src/l10n/generated
arb-dir: ./lib/src/l10n
template-arb-file: intl_en.arb
output-localization-file: inventory_localizations.dart
output-class: InventoryLocalizations