// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('buy', function () {
  this.timeout(5000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('buy', async function () {
    // Test name: buy
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://100000.localhost:8080/")
    // 2 | setWindowSize | 1618x879 | 
    await driver.manage().window().setRect({ width: 1618, height: 879 })
    // 3 | click | css=.active:nth-child(2) > .d-block:nth-child(1) .figure-img | 
    await driver.findElement(By.css(".active:nth-child(1) > .d-block:nth-child(1) .figure-img")).click()
    // 4 | click | id=cartAdd | 
    await driver.findElement(By.id("cartAdd")).click()
    // 5 | click | css=.nav-item:nth-child(3) > .nav-link | 
    await driver.findElement(By.css(".nav-item:nth-child(3) > .nav-link")).click()
    // 6 | click | css=.btn-create-account | 
    await driver.findElement(By.css(".btn-create-account")).click()
    // 7 | click | css=.form-group:nth-child(3) .form-control | 
    //    await driver.findElement(By.css(".form-group:nth-child(3) .form-control")).click()
    // 8 | type | css=.form-group:nth-child(3) .form-control | test11first
    await driver.findElement(By.css(".form-group:nth-child(3) .form-control")).sendKeys("test12first")
    // 9 | type | css=.form-group:nth-child(4) .form-control | test11last
    await driver.findElement(By.css(".form-group:nth-child(4) .form-control")).sendKeys("test12last")
    // 10 | type | css=.form-group:nth-child(5) .form-control | test11@example.com
    await driver.findElement(By.css(".form-group:nth-child(5) .form-control")).sendKeys("test12@example.com")
    // 11 | click | css=.btn-login | 
    await driver.findElement(By.css(".btn-login")).click()
    // 12 | click | css=.btn-login | 
    await driver.findElement(By.css(".btn-login")).click()
    // 13 | click | css=.nav-item:nth-child(2) > .nav-link | 
    await driver.findElement(By.css(".nav-item:nth-child(2) > .nav-link")).click()
    // 14 | click | linkText=Add a New Address | 
    await driver.findElement(By.linkText("Add a New Address")).click()
    // 15 | click | id=name | 
    await driver.findElement(By.id("name")).click()
    // 16 | type | id=name | addr
    await driver.findElement(By.id("name")).sendKeys("addr")
    // 17 | click | id=address1 | 
    await driver.findElement(By.id("address1")).click()
    // 18 | type | id=address1 | addr2
    await driver.findElement(By.id("address1")).sendKeys("addr2")
    // 19 | type | id=city | bangdi
    await driver.findElement(By.id("city")).sendKeys("bangdi")
    // 20 | type | id=postalcode | 222222
    await driver.findElement(By.id("postalcode")).sendKeys("222222")
    // 21 | click | css=.flex-fill > span | 
    await driver.findElement(By.css(".flex-fill > span")).click()
    // 22 | click | css=.checkmark | 
    await driver.findElement(By.css(".checkmark")).click()
    // 23 | click | css=.btn-continue | 
    await driver.findElement(By.css(".btn-continue")).click()
    // 24 | click | css=.btn-continue | 
    await driver.findElement(By.css(".btn-continue")).click()
    // 25 | click | linkText=Add a Credit Card | 
    await driver.findElement(By.linkText("Add a Credit Card")).click()
    // 26 | click | id=nameCard | 
    await driver.findElement(By.id("nameCard")).click()
    // 27 | type | id=nameCard | test11
    await driver.findElement(By.id("nameCard")).sendKeys("test11")
    // 28 | click | id=card | 
    await driver.findElement(By.id("card")).click()
    // 29 | type | id=card | 4012888888881881
    await driver.findElement(By.id("card")).sendKeys("4012888888881881")
    // 30 | click | css=.d-flex > .form-control:nth-child(1) | 
    await driver.findElement(By.css(".d-flex > .form-control:nth-child(1)")).click()
    // 31 | select | css=.d-flex > .form-control:nth-child(1) | label=05
    {
      const dropdown = await driver.findElement(By.css(".d-flex > .form-control:nth-child(1)"))
      await dropdown.findElement(By.xpath("//option[. = '05']")).click()
    }
    // 32 | click | css=.form-control:nth-child(1) > option:nth-child(6) | 
    await driver.findElement(By.css(".form-control:nth-child(1) > option:nth-child(6)")).click()
    // 33 | click | css=.form-control:nth-child(2) | 
    await driver.findElement(By.css(".form-control:nth-child(2)")).click()
    // 34 | select | css=.form-control:nth-child(2) | label=2026
    {
      const dropdown = await driver.findElement(By.css(".form-control:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = '2026']")).click()
    }
    // 35 | click | css=.ml-3 > option:nth-child(4) | 
    await driver.findElement(By.css(".ml-3 > option:nth-child(4)")).click()
    // 36 | click | css=.form-group:nth-child(4) > .col-12 > .form-control | 
    await driver.findElement(By.css(".form-group:nth-child(4) > .col-12 > .form-control")).click()
    // 37 | select | css=.form-group:nth-child(4) > .col-12 > .form-control | label=addr, addr2, bangdi
    {
      const dropdown = await driver.findElement(By.css(".form-group:nth-child(4) > .col-12 > .form-control"))
      await dropdown.findElement(By.xpath("//option[. = 'addr, addr2, bangdi']")).click()
    }
    // 38 | click | css=.col-12 option:nth-child(2) | 
    await driver.findElement(By.css(".col-12 option:nth-child(2)")).click()
    // 39 | click | css=.button-spacing span | 
    await driver.findElement(By.css(".button-spacing span")).click()
    // 40 | click | id=cvv | 
    await driver.findElement(By.id("cvv")).click()
    // 41 | type | id=cvv | 999
    await driver.findElement(By.id("cvv")).sendKeys("999")
    // 42 | click | css=.btn-continue | 
    await driver.findElement(By.css(".btn-continue")).click()
    // 43 | click | css=.btn-place-order | 
    await driver.findElement(By.css(".btn-place-order")).click()
    // 44 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 45 | click | linkText=Keep Shopping | 
    await driver.findElement(By.linkText("Keep Shopping")).click()
    // 46 | click | linkText=test11first test11last | 
    await driver.findElement(By.linkText("test11first test11last")).click()
    // 47 | click | css=form > .dropdown-item | 
    await driver.findElement(By.css("form > .dropdown-item")).click()
  })

  after(async () => await driver.quit());
})
