// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('login', async function () {
    await driver.get("http://100000.localhost:8080/")
    await driver.manage().window().setRect({ width: 1510, height: 771 })
    await driver.findElement(By.linkText("Log In")).click()
    await driver.findElement(By.css(".btn-login")).click()
    await driver.findElement(By.id("navbarMenuAccount")).click()
    await driver.findElement(By.linkText("Logout")).click()
  })
})
