preferred-supported-locales: [en, th]
synthetic-package: false
output-dir: ./lib/src/l10n/generated
arb-dir: ./lib/src/l10n
template-arb-file: intl_en.arb
output-localization-file: activity_localizations.dart
output-class: ActivityLocalizations