name: models
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  decimal: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
